AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless trigger-based application

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON

Resources:
  MidasSendScraperDataSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "MidasSendScraperDataSNS.fifo"
      FifoTopic: true
      ContentBasedDeduplication: true

  MidasSendScraperDataSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MidasSendScraperDataSNS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "SNS:Subscribe"
            Resource: !Ref MidasSendScraperDataSNS

  MidasSaveDataSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "MidasSaveDataSQS.fifo"
      FifoQueue: true

  Subscriptions:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref MidasSendScraperDataSNS
      Endpoint: !GetAtt MidasSaveDataSQS.Arn

  MidasSaveDataSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MidasSaveDataSQS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource: !GetAtt MidasSaveDataSQS.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MidasSendScraperDataSNS

  MidasSaveDataLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      FunctionName: MidasSaveDataLambdaFunction
      Architectures:
      - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MidasSaveDataSQS.Arn

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda Function"
    Value: !GetAtt MidasSaveDataLambdaFunction.Arn
  MidasSendScraperDataSNSArn:
    Description: "ARN of the SNS Topic"
    Value: !Ref MidasSendScraperDataSNS
  MidasSaveDataSQSArn:
    Description: "ARN of the SQS Queue"
    Value: !GetAtt MidasSaveDataSQS.Arn